# File node0.toml

[parity]
chain = "spec.json"
base_path = "node"

[network]
port = 30300
#bootnodes = []

[rpc]
disable = true

[websockets]
disable = true

[account]
password = ["node.pwd"]

[mining]
engine_signer = "0x247ac17f40680f621607560ea21c2defe41b4b4e"
reseal_on_txs = "none"
force_sealing = true

